/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class czmc_com_graldetest_JniUtils */

#ifndef _Included_czmc_com_graldetest_JniUtils
#define _Included_czmc_com_graldetest_JniUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     czmc_com_graldetest_JniUtils
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_czmc_com_graldetest_JniUtils_init
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
